tags:
- name: auth
  description: auth API
- name: breweries
  description: breweries API

paths:
# [POST] login
  /login:
    get:
      tags:
      - auth
      summary: Login with an email and a password
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'


# [POST] logout
  /logout:
    post:
      tags:
      - auth
      summary: Logout from the application
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [POST] signup
  /signup:
    post:
      tags:
      - auth
      summary: Creates a new user
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] breweries
  /breweries:
    get:
      tags:
      - breweries
      summary: Get breweries data transformed
      responses:
        200:
          description: 'Created'
        401:
          description: 'Unauthorized'
        500:
          description: 'Server Error'

# definitions
definitions:
  users:
    type: object
    required:
        - email
        - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
